# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 460)
        MainWindow.setStyleSheet("background-color: rgb(220,220,220);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(81, 81, 81);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 210, 411))
        self.frame.setStyleSheet("background-color: rgb(250, 250,250);\n"
"border: 2px solid  rgb(120, 120, 120);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgb(50, 50, 50);\n"
"  border: 0px ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(0, 60, 210, 350))
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(210, 0, 210, 411))
        self.frame_2.setStyleSheet("background-color: rgb(250, 250,250);\n"
"border: 2px solid  rgb(120, 120, 120);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:  rgb(50, 50, 50);\n"
"  border: 0px ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineLogin = QtWidgets.QLineEdit(self.frame_2)
        self.lineLogin.setGeometry(QtCore.QRect(20, 120, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineLogin.setFont(font)
        self.lineLogin.setStyleSheet("background-color: rgb(220,220,220);\n"
"border: 2px solid  rgb(120,120,120);\n"
"border-radius: 20;")
        self.lineLogin.setObjectName("lineLogin")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 94, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:  rgb(0, 0, 0);\n"
"border: 0px ")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:  rgb(0, 0, 0);\n"
"border: 0px ")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:  rgb(0, 0, 0);\n"
"border: 0px ")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.linePass = QtWidgets.QLineEdit(self.frame_2)
        self.linePass.setGeometry(QtCore.QRect(20, 210, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.linePass.setFont(font)
        self.linePass.setStyleSheet("background-color: rgb(220,220,220);\n"
"border: 2px solid  rgb(120,120,120);\n"
"border-radius: 20;")
        self.linePass.setObjectName("linePass")
        self.lineComment = QtWidgets.QLineEdit(self.frame_2)
        self.lineComment.setGeometry(QtCore.QRect(20, 300, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineComment.setFont(font)
        self.lineComment.setStyleSheet("background-color: rgb(220,220,220);\n"
"border: 2px solid  rgb(120,120,120);\n"
"border-radius: 20;")
        self.lineComment.setObjectName("lineComment")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 410, 420, 50))
        self.frame_3.setStyleSheet("background-color: rgb(250, 250,250);\n"
"border: 2px solid  rgb(120, 120, 120);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(320, 10, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setToolTipDuration(-1)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:  rgb(30, 30, 30);\n"
"    background-color: rgb(200, 200, 200);\n"
"    border: 2px solid  rgb(120, 120, 120);\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    backlground-color: rgb(80, 80, 80)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Список паролей"))
        self.label_2.setText(_translate("MainWindow", "Редактирование"))
        self.label_3.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Comment"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Записать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
